### ISSUE TITLE
Install edge-connexion module and open connection from OCLC Connexion Client

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#158]
https://github.com/folio-org/edge-connexion

From Vitus:

> This message is for the LibSys Folio team regarding configuring the OCLC Connexion client to push records into Folio.
> [Folio documentation](https://wiki.folio.org/display/FOLIOtips/Single+Record+Import) says:
> Configure the Host Name to be {folio environment}-edge.dev.folio.org where {folio environment} is one of:
> folio-snapshot
> folio-testing
> folio-snapshot-load
> The Port should be 9000
> The Logon Id is and API key that is used to specify a system user to the edge-connexion module. Enter this value: eyJzIjoiblo1NkYzTGVBYSIsInQiOiJkaWt1IiwidSI6ImRpa3UifQ==
> So, I am looking for the equivalent Host name, Port, and logon id for our folio-test.stanford.edu environment. Could someone send me those?

**Comment by jgreben** [comment]
Jason Root
  9:24 AM
Ah - “edge-common” is not really something you need to deploy on to your K8s cluster. Rather, it is the “base-line” that the edge modules are built from.
For the ephemeral.properties , I use a K8s Secret and mount that inside all of the various edge-blahblahblah deployments that we use.
To generate the API key, I followed the instructions and did all of the foo on my local iMac.

...

Jason Root
  9:27 AM
Yeah, just download the https://github.com/folio-org/edge-common repo onto your local machine (or to some central jumpbox if you need to) and run the commands after you have all the required binaries.


Joshua Greben
  9:28 AM
so whatever edge-common spits out, add that to k8s secret and then modify the chart to deploy that with secretKeyRef and name ephemeral.properties ?


Jason Root
  9:29 AM
You actually won’t need to add the API key to the edge-ephemeral.properties - the API key is used on the request when you go to connect to one of the edge module API endpoints. (edited) 

...

Jason Root
  9:32 AM
Now if you’re using VaultStore or AWSParamStore then you’ll need the foo of the parameters for the retrieval.
What you will need to do is in Folio, create an “institutional user” and assign it the appropriate permissions that the edge module’s API needs to interact with your Folio system. (edited) 
9:34
For the edge module Workloads in K8s, I’m setting this env var:
JAVA_OPTIONS = -XX:MaxRAMPercentage=66.0 -Dokapi_url=http://okapi:9130 -Dsecure_store=Ephemeral -Dsecure_store_props=/etc/folio/edge/edge-ephemeral.properties -Dapi_key_sources=PARAM,HEADER,PATH -Dlog4j2.formatMsgNoLookups=true (edited) 


Joshua Greben
  9:35 AM
Is that what do you mean by mounting the k8s secret inside the edge-module?


Jason Root
  9:36 AM
Ah, so my Secret is the edge-ephemeral.properties file:
```
edge-ephemeral.properties =
secureStore.type=Ephemeral
\# a comma separated list of tenants
tenants=tamu
#######################################################
\# For each tenant, the institutional user password...
\#
\# Note: this is intended for development purposes only
#######################################################
\# format: tenant=username,password
tamu=edgeuser,<password>
```

Joshua Greben
  9:37 AM
so you do actually mount that in the pod?
:+1:
1



Jason Root
  9:37 AM
That Secret is mounted as a Volume at a path:
```
        volumeMounts:
        - mountPath: /etc/folio/edge
          name: edge-ephemeral
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: edge-ephemeral
        secret:
          defaultMode: 420
          optional: true
          secretName: edge-securestore-props
```
