### ISSUE TITLE
Patron group mappings needed for tsv_users:load_tsv_users_file 

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#464]
Two more mappings are needed for patron groups for the rake task:
rake tsv_users:load_tsv_users_file[expired_users_to_migrate.tsv] 

MXD-RLCP -> graduate
PSEUDO -> pseudopatron

These users won’t come from the registry.  They will be migrated to FOLIO is user has loans or bills that need migrating, and user is expired (plus the pseudo patrons).

**Comment by jgreben** [comment]
I updated my local settings files and also the ones in vault
```
$ vault kv list /puppet/application/folio-tasks/config/settings/
Keys
----
dev
prod
stage
uat
```
and also and the one on bodoni.

```
courtesygroups:
  ASSO-BDRCT: SUL-institution
  DOC-RLCPB: SUL-institution
  DOC-RLCPT: SUL-institution
  DOC-RSP: SUL-institution
  FAC-RLCPB: SUL-institution
  FAC-RLCPT: SUL-institution
  FAC-RSP: SUL-institution
  MXALUM-LAW: law-guest
  MXAS-25LMT: SUL-guest
  MXD-RLCP: graduate
  MXFEE: SUL-fee
  MXFEE-BUS: BUS-guest
  MXFEE-NO25: SUL-fee
  PSEUDO: pseudopatron
```
